### create a ticket
POST http://localhost:8080/api/tickets
Content-Type: application/json

{
  "title": "Laptop not starting",
  "description": "Laptop shows black screen",
  "status": "OPEN",
  "priority": "HIGH"
}

### Get all ticket

GET http://localhost:8080/api/tickets

### Get ticket by ID

GET http://localhost:8080/api/tickets/999


### Update ticket 1

PUT http://localhost:8080/api/tickets/1
Content-Type: application/json

{
  "title": "Laptop not starting",
  "description": "Laptop shows black screen",
  "status": "IN_PROGRESS",
  "priority": "HIGH"
}

### Create second ticket

POST http://localhost:8080/api/tickets
Content-Type: application/json

{
  "title": "login problem",
  "description": "Unable to login to company laptop",
  "status": "OPEN",
  "priority": "MEDIUM"
}

### Delete ticket 2

DELETE http://localhost:8080/api/tickets/2

### all available ticket after CRUD operation
GET http://localhost:8080/api/tickets

### after the service layer build
POST http://localhost:8080/api/tickets
Content-Type: application/json

{
  "title": "Printer not working",
  "description": "Office printer is offline",
  "status": "OPEN",
  "priority": "HIGH"
}
### responce filter by status
GET http://localhost:8080/api/tickets/status/OPEN

### responce filter by priority
GET http://localhost:8080/api/tickets/priority/HIGH

### filtering by status and priority
GET http://localhost:8080/api/tickets/status/OPEN/priority/HIGH

### filtering using request and geting responce
GET http://localhost:8080/api/tickets/filter

### filtering using request and geting status responce
GET http://localhost:8080/api/tickets/filter?status=OPEN


### filtering using request and geting priority responce
GET http://localhost:8080/api/tickets/filter?priority=HIGH


### filtering using request and geting status and priority responce
GET http://localhost:8080/api/tickets/filter?status=OPEN&priority=HIGH

### Ticket responce as ID Asending
GET http://localhost:8080/api/tickets

### ticket responce as ID Decending
GET http://localhost:8080/api/tickets?sortBy=id&direction=desc

### sorting by priority
GET http://localhost:8080/api/tickets?sortBy=priority&direction=asc

### sorting and filtering together
GET http://localhost:8080/api/tickets/filter?status=OPEN&sortBy=id&direction=desc

### test priority and sorting
GET http://localhost:8080/api/tickets/filter?priority=HIGH&sortBy=id&direction=desc

### sorting with paging and fixed number of size
GET http://localhost:8080/api/tickets?page=1&size=2&sortBy=id&direction=desc

### Combine Filtering + Sorting + Pagination in one endpoint

GET http://localhost:8080/api/tickets/filter?status=OPEN&priority=HIGH&sortBy=id&direction=desc&page=0&size=2